import {
  AppleIcon,
  BeefIcon,
  BeerIcon,
  CakeIcon,
  CoffeeIcon,
  CookingPotIcon,
  CupSodaIcon,
  HamIcon,
  IceCreamBowlIcon,
  IceCreamConeIcon,
  PizzaIcon,
  PopcornIcon,
  SaladIcon,
  SandwichIcon,
  SoupIcon,
  UtensilsIcon,
} from 'lucide-react'

export const icons = [
  { id: 'utensils', icon: UtensilsIcon },
  { id: 'beef', icon: BeefIcon },
  { id: 'apple', icon: AppleIcon },
  { id: 'cooking-pot', icon: CookingPotIcon },
  { id: 'ham', icon: HamIcon },
  { id: 'ice-cream-bowl', icon: IceCreamBowlIcon },
  { id: 'ice-cream-cone', icon: IceCreamConeIcon },
  { id: 'pizza', icon: PizzaIcon },
  { id: 'salad', icon: SaladIcon },
  { id: 'sandwich', icon: SandwichIcon },
  { id: 'soup', icon: SoupIcon },
  { id: 'beer', icon: BeerIcon },
  { id: 'coffee', icon: CoffeeIcon },
  { id: 'cup-soda', icon: CupSodaIcon },
  { id: 'popcorn', icon: PopcornIcon },
  { id: 'cake', icon: CakeIcon },
]
