import {
  AppleIcon,
  BeefIcon,
  BeerIcon,
  CakeIcon,
  CoffeeIcon,
  CookingPotIcon,
  CupSodaIcon,
  HamIcon,
  IceCreamBowlIcon,
  IceCreamConeIcon,
  PizzaIcon,
  PopcornIcon,
  SaladIcon,
  SandwichIcon,
  SoupIcon,
  UtensilsIcon,
} from 'lucide-react'

export const icons = {
  utensils: UtensilsIcon,
  beef: BeefIcon,
  apple: AppleIcon,
  'cooking-pot': CookingPotIcon,
  ham: HamIcon,
  'ice-cream-bowl': IceCreamBowlIcon,
  'ice-cream-cone': IceCreamConeIcon,
  pizza: PizzaIcon,
  salad: SaladIcon,
  sandwich: SandwichIcon,
  soup: SoupIcon,
  beer: BeerIcon,
  coffee: CoffeeIcon,
  'cup-soda': CupSodaIcon,
  popcorn: PopcornIcon,
  cake: CakeIcon,
}
